### ISSUE TITLE
WebIDF CloudFormation quicklink, failing to deploy

### ISSUE THREAD

**Issue by EGStrain** [acantril/learn-cantrill-io-labs#109]
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/quickcreate?templateURL=https://learn-cantrill-labs.s3.amazonaws.com/aws-cognito-web-identity-federation/WEBIDF.yaml&stackName=WEBIDF

I am seeing:

Logical ID: appbucket 
Status: Create_Failed 
Status Reason: API: s3:CreateBucket Access Denied

With the following as being the Status Reason for CloudFormation to fail to deploy:

The following resource(s) failed to create: [appbucket, patchesprivatebucket]. Rollback requested by user.

Logged in with Admin user in us-east-1 before deployment. It's possible that it's trying to create a bucket named appbucket which may already exist in another account (due to global namespace).

**Comment by EGStrain** [comment]
To clarify, this was from the lesson available here:

https://learn.cantrill.io/courses/aws-certified-solutions-architect-professional/lectures/24435345

**Comment by acantril** [comment]
Hi
I notice you work for AWS, are you trying to create this in an AWS account provided by AWS ? if so, they prevent you creating buckets which are public.

**Comment by EGStrain** [comment]
Yes, using internal account, will confirm.
