### ISSUE TITLE
Database Migration Service-STAGE1: CatWeb webserver does not work

### ISSUE THREAD

**Issue by maxritter** [acantril/learn-cantrill-io-labs#13]
I spawned the CloudFormation template into N.Virginia, but even one hour after it was successfully deployed, the CatWeb webserver is still not reachable over its public IP/DNS.. 
Would be great if you can fix this, so I can continue with the Lab in the Architect Pro course :)

**Comment by maxritter** [comment]
awsCatWeb in STAGE3 does also not show anything after the files have been copied and permissions fixed..

**Comment by acantril** [comment]
Hi Max
I've just tested this and it seems to work fine
I wanted to confirm that you are actually copying the IP address down, and
opening in a new tab (which uses HTTP by default) vs clicking the 'open
address' link next to the IP, which uses HTTPS which doesn't work.
The instructions do say copy the IP and open it in a new tab, but ive had 1
or 2 students use the other incorrect method.
My tests show no problems with the demo at all.
/Adrian

**Comment by maxritter** [comment]
Oh my gosh, that was it, I feel so stupid now :D Sometimes it's the small things..
Thanks for your quick answer and for the awesome courses that you provide, really appreciate it!
