### ISSUE TITLE
Pet-Cuddle-O-Tron - STAGE 3B ASL code does not match video

### ISSUE THREAD

**Issue by H-Adrian** [acantril/learn-cantrill-io-labs#141]
[The link at this line](https://github.com/acantril/learn-cantrill-io-labs/blob/b4739d8b1c82b7171a397ecafc1be45e3b216c54/aws-serverless-pet-cuddle-o-tron/02_LABINSTRUCTIONS/STAGE3%20-%20Implement%20and%20Configure%20State%20Machine.md?plain=1#L42C3-L42C3) which looks like this:
```
{
  "Comment": "Pet Cuddle-o-Tron - using Lambda for email.",
  "StartAt": "Timer",
  "States": {
    "Timer": {
      "Type": "Wait",
      "SecondsPath": "$.waitSeconds",
      "Next": "Email"
    },
    "Email": {
      "Type" : "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "Parameters": {
        "FunctionName": "EMAIL_LAMBDA_ARN",
        "Payload": {
          "Input.$": "$"
        }
      },
      "Next": "NextState"
    },
    "NextState": {
      "Type": "Pass",
      "End": true
    }
  }
}

```
that contains the ASL code does not match the code shown in the video:
![image](https://github.com/acantril/learn-cantrill-io-labs/assets/21315305/2c53e35e-a930-44f8-896c-64f5d8b955cf)

Am I doing something wrong? Otherwise I'm surprised this has been like this for 3 years if that's the case.

**Comment by acantril** [comment]
Where are you watching this video ? the image you paste seems to be out of date and i've updated it since then.

**Comment by imranshs08** [comment]
Zzzzzzzzz,zzzzx
