### ISSUE TITLE
CloudFront caching causes this demo to not work (at least for me)

### ISSUE THREAD

**Issue by kenmillard** [acantril/learn-cantrill-io-labs#142]
[MINIPROJECT] Implementing Web Identity Federation (WEBIDF) - PART4

For this lab, if the student opens the CloudFront URI before the index.html and scripts.js are updated, it will cache those files for the next 24 hours (and keep the student from completing the lab).  

I found that I had to go into CloudFront > Distributions > select my Distribution > Invalidations, then add these two invalidations:
/index.html
/scripts.js

After that, it reloaded my updated files from the S3 bucket and let me open it.  For those who get stuck here, it may be something to add to the instructions.  Thanks!

**Comment by acantril** [comment]
Hi this is already in the instructions under "Caching Issue"
Thanks for reporting anyway though.

**Comment by kenmillard** [comment]
LOL, I totally missed that.  Reading would've saved me a few minutes.  Thanks for the response!
