### ISSUE TITLE
Update the bash script

### ISSUE THREAD

**Issue by sogwujiakwu** [acantril/learn-cantrill-io-labs#156]
Script needs to be updated as follows
 
#!/bin/bash
source <(php -r 'require("/var/www/html/wp-config.php"); echo("DB_NAME=".DB_NAME."; DB_USER=".DB_USER."; DB_PASSWORD=".DB_PASSWORD."; DB_HOST=".DB_HOST); ')
SQL_COMMAND="mysql -u $DB_USER -h $DB_HOST -p$DB_PASSWORD $DB_NAME -e"
OLD_URL=$(mysql -u $DB_USER -h $DB_HOST -p$DB_PASSWORD $DB_NAME -e 'select option_value from wp_options where option_id = 1;' | grep http)
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
HOST=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/public-hostname)

$SQL_COMMAND "UPDATE wp_options SET option_value = replace(option_value, '$OLD_URL', 'http://$HOST') WHERE option_name = 'home' OR option_name = 'siteurl';"
$SQL_COMMAND "UPDATE wp_posts SET guid = replace(guid, '$OLD_URL','http://$HOST');"
$SQL_COMMAND "UPDATE wp_posts SET post_content = replace(post_content, '$OLD_URL', 'http://$HOST');"
$SQL_COMMAND "UPDATE wp_postmeta SET meta_value = replace(meta_value,'$OLD_URL','http://$HOST');"

**Comment by acantril** [comment]
What bash script ?
you've logged this as an issue, it's not linked to a specific file.

**Comment by sogwujiakwu** [comment]
it is related to this file [learn-cantrill-io-labs](https://github.com/acantril/learn-cantrill-io-labs/tree/master)/[aws-dms-database-migration](https://github.com/acantril/learn-cantrill-io-labs/tree/master/aws-dms-database-migration)/[02_LABINSTRUCTIONS](https://github.com/acantril/learn-cantrill-io-labs/tree/master/aws-dms-database-migration/02_LABINSTRUCTIONS)
/STAGE4 - Migrate Database & Cutover.md
