### ISSUE TITLE
 Advanced Site-to-Site VPN - STAGE4

### ISSUE THREAD

**Issue by MohamedAYACH** [acantril/learn-cantrill-io-labs#28]
./ffrouting-install.sh returns errors

configure: error: libyang (>= 2.0.0) was not found on your system.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
install: cannot stat 'tools/frr.service': No such file or directory
Failed to enable unit: Unit file frr.service does not exist.
Failed to start frr.service: Unit frr.service not found.

**Comment by acantril** [comment]
Hi - I've updated these scripts again, newer versions required a new library to be installed which I've added.
thanks for the heads up.
