### ISSUE TITLE
[AdvancedDemo] Architecture Evolution - STAGE2

### ISSUE THREAD

**Issue by MohamedAYACH** [acantril/learn-cantrill-io-labs#31]
Hello,

The user data does not excecute.

thx in advance

**Comment by acantril** [comment]
you have probably missed one or more of the SSM parameter store values you should have added in the setup part of the demo. Have you added DBName, DBUser and the others ?

**Comment by MohamedAYACH** [comment]
Hello,

thx for you quick response, I did when I put it manually form the launched EC2 it grabs the parameters stores...

**Comment by ryanef** [comment]
> Hello,
> 
> thx for you quick response, I did when I put it manually form the launched EC2 it grabs the parameters stores...
> 
> When I Echo $DBPassword from the created instance I get nothing so I run the command manually:
> 
> ```
> DBPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBPassword --with-decryption --query Parameters[0].Value)
> DBPassword=`echo $DBPassword | sed -e 's/^"//' -e 's/"$//'`
> ```
> 
> and run ECHO $DBPassword again it shows.
> 
> ![2021-07-08 12_01_42-AWS Systems Manager - Parameter Store and 4 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/84203648/124911204-64b43000-dfe4-11eb-8f8d-c5c01e314448.png)

I changed

`DBPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBPassword --with-decryption --query Parameters[0].Value)
DBPassword=`echo $DBPassword | sed -e 's/^"//' -e 's/"$//'`

DBRootPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBRootPassword --with-decryption --query Parameters[0].Value)
DBRootPassword=`echo $DBRootPassword | sed -e 's/^"//' -e 's/"$//'`

DBUser=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBUser --query Parameters[0].Value)
DBUser=`echo $DBUser | sed -e 's/^"//' -e 's/"$//'`

DBName=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBName --query Parameters[0].Value)
DBName=`echo $DBName | sed -e 's/^"//' -e 's/"$//'`

DBEndpoint=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBEndpoint --query Parameters[0].Value)
DBEndpoint=`echo $DBEndpoint | sed -e 's/^"//' -e 's/"$//'``

to

`DBPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBPassword --with-decryption --query Parameters[0].Value)
DBPassword=`echo $DBPassword | sed -e 's/^"//' -e 's/"$//'`

DBRootPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBRootPassword --with-decryption --query Parameters[0].Value)
DBUser=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBUser --query Parameters[0].Value)
DBName=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBName --query Parameters[0].Value)
DBEndpoint=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBEndpoint --query Parameters[0].Value)
`

and it worked for me

**Comment by ryanef** [comment]
When I changed the user data to look like this
`DBPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBPassword --with-decryption --query Parameters[0].Value | tr -d \")
DBRootPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBRootPassword --with-decryption --query Parameters[0].Value | tr -d \" | tr -d \")
DBUser=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBUser --query Parameters[0].Value | tr -d \")
DBName=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBName --query Parameters[0].Value | tr -d \")
DBEndpoint=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBEndpoint --query Parameters[0].Value | tr -d \")`

it worked. I removed the lines with the echo

**Comment by ryanef** [comment]
I updated the user data variables section to look like this and it worked

`DBPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBPassword --with-decryption --query Parameters[0].Value | tr -d \")

DBRootPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBRootPassword --with-decryption --query Parameters[0].Value | tr -d \" | tr -d \")

DBUser=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBUser --query Parameters[0].Value | tr -d \")

DBName=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBName --query Parameters[0].Value | tr -d \")

DBEndpoint=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBEndpoint --query Parameters[0].Value | tr -d \")
`

I don't know why removing the lines with the echo worked but I'm up and running now

**Comment by ryanef** [comment]
```
DBPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBPassword --with-decryption --query Parameters[0].Value | tr -d \")
DBRootPassword=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBRootPassword --with-decryption --query Parameters[0].Value | tr -d \" | tr -d \")
DBUser=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBUser --query Parameters[0].Value | tr -d \")
DBName=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBName --query Parameters[0].Value | tr -d \")
DBEndpoint=$(aws ssm get-parameters --region us-east-1 --names /A4L/Wordpress/DBEndpoint --query Parameters[0].Value | tr -d \")
```

updating the User Data variables section to look like that worked for me. I don't know why but removing the lines with the echo worked.

**Comment by acantril** [comment]
did you do any different config with the AWS cli ? change the output format or anything ?

**Comment by acantril** [comment]
the change you have made @ryanef look to handle a different structure output from the SSM CLI interaction

**Comment by ryanef** [comment]
@acantril It's what I found in the post by "Update for Advanced Demo - Web App - Single Server to Elastic Evolution - STAGE 2" from earlier this year. I was stumped after double checking the parameters I put into Systems Manager so gave that a shot and it worked for some reason.

**Comment by acantril** [comment]
That didn't really answer my question...i've just tested the demo and it worked fine as is. It means you did something 'different' and I'm trying to work out what it is :)

**Comment by acantril** [comment]
closing because no comments.
