### ISSUE TITLE
API_Lambda.py did not run

### ISSUE THREAD

**Issue by peterneave** [acantril/learn-cantrill-io-labs#40]
Code within https://learn-cantrill-labs.s3.amazonaws.com/aws-serverless-pet-cuddle-o-tron/api_lambda.py needed to be modified for me to run the lambda.

Line 17:
Change to: `    data = event`

There was no body.

**Comment by acantril** [comment]
if this is the case, then you configured another part of the demo wrongly which can influence the data structure lambda receives. Your fix worked, but your fix.. fixed an earlier error :)

**Comment by palayoov** [comment]
Hit this error too, helped to see the event structure before and after the method level proxy integration was enabled.

**Comment by acantril** [comment]
to be clear about this ... there is nothing wrong with the code
for anyone getting this error, a configuration issue was made during the setup.
