### ISSUE TITLE
Rate limit issue from Docker Hub in "catpipeline" Demo

### ISSUE THREAD

**Issue by thomasdpage** [acantril/learn-cantrill-io-labs#55]
In this lesson of the demo:  https://github.com/acantril/learn-cantrill-io-labs/blob/master/aws-codepipeline-catpipeline/02_LABINSTRUCTIONS/STAGE2-CODEBUILD.md

The docker build fails due to a rate limit on Docker Hub on the Centos base image.

```
Step 1/7 : FROM centos:7
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by thomasdpage** [comment]
Fixed by chaning the following in the Dockerfile:

`FROM centos:7`

To 

`FROM public.ecr.aws/docker/library/centos:7`

There already seems to be a pull request open for this but I will leave this here for others.

**Comment by iainbrux** [comment]
Bumping this as I too ran into this issue. Doing the aforementioned solved the issue.

**Comment by ArtistYay** [comment]
> Fixed by changing the following in the Dockerfile:
> 
> `FROM centos:7`
> 
> To
> 
> `FROM public.ecr.aws/docker/library/centos:7`
> 
> There already seems to be a pull request open for this but I will leave this here for others.

Hey Thomas, is it possible you can explain how you came to that conclusion/solved the problem?

**Comment by thomasdpage** [comment]
@ArtistYay it was a while ago now, but I'll try :-)

So, the error message I included when I raised this issue is (I think) due to DockerHub's rate limit issue (it used to be free and now it's not).  Centos is no longer in development/support I believe, so this combined with DockerHub's rate limit/fees was the cause.  

AWS built a [public ECR gallery](https://gallery.ecr.aws) (equivalent to DockHub when it was free) so I use that instead.

Hope this helps.

**Comment by ArtistYay** [comment]
> @ArtistYay it was a while ago now, but I'll try :-)
> 
> So, the error message I included when I raised this issue is (I think) due to DockerHub's rate limit issue (it used to be free and now it's not). Centos is also no longer in development/support I believe, so this combined with DockerHub's rate limit/fees was the cause.
> 
> AWS built a [public ECR gallery](https://gallery.ecr.aws) (equivalent to DockHub when it was free) so I used that instead.
> 
> Hope this helps.

Yes sir helped a lot! Thank you!

**Comment by acantril** [comment]
Demo updated to use ECR
