### ISSUE TITLE
CloudFormation Template error

### ISSUE THREAD

**Issue by Prashanthjs86** [acantril/learn-cantrill-io-labs#7]
The CF templates provided for Advanced Site-to-Site VPN Demo (AWS and ONPREM) are not working.

**Comment by acantril** [comment]
what about them doesn't work ?

**Comment by Prashanthjs86** [comment]
![Screenshot 2020-12-04 124436](https://user-images.githubusercontent.com/20902861/101133424-b780d000-362e-11eb-9081-cb3d0aae17e3.png)

**Comment by acantril** [comment]
Why are you downloading the then uploading the templates like that?
there are 1-click deployments here
https://github.com/acantril/learn-cantrill-io-labs/tree/master/AWS_HYBRID_AdvancedVPN
scroll down.
If you are downloading and then uploading ... are you clicking the 'RAW'
button to get the actual templates? or saving the HTML page and trying to
then use those ?
What instructions are you following to be doing what you are doing ?

**Comment by Prashanthjs86** [comment]
I downloaded and uploaded them as YAML files. 
Thanks for pointing out1-click deployments!
