### ISSUE TITLE
MySQL RDS - Aurora compatibility issue

### ISSUE THREAD

**Issue by paoloromagnoli** [acantril/learn-cantrill-io-labs#77]
First of all, thanks for sharing this lab. This is pretty useful. 

In stage 3 you suggest to select MySQL version 8.0.28 for best Aurora compatibility for snapshot migrations. However when in stage 6 I try to execute the migrate snapshot action it fails with error connected to MySQL engine compatibility issue between snapshot MySQL 8.0.28 and Aurora MySQL 8.0.23 (there is no way to pick another MySQL version for Aurora). I fixed this by creating a new RDS MySQL 8.0.23 instance, migrating the WordPress DB on this new RDS instance and then catching up with your instructions. Can I suggest to amend stage 3 MySQL version suggestion?

**Comment by Arka21Pal** [comment]
Would you like to do a pull request, such that it makes it easier to Adrian to see the changes?

**Comment by acantril** [comment]
Hi.. stage 3 of what ?
and yeah a PR is always better. thanks.

**Comment by paoloromagnoli** [comment]
Sorry, my description is not clear. I am referring to aws-elastic-wordpress-evolution https://github.com/acantril/learn-cantrill-io-labs/tree/master/aws-elastic-wordpress-evolution. I am going to (try) do pull request for this
