### ISSUE TITLE
Advanced Hybrid Directory - STAGE 2E - Connect to the 'client' instance

### ISSUE THREAD

**Issue by ptal3** [acantril/learn-cantrill-io-labs#78]
Hi @acantril,

Loving your course. The fundamentals are a godsend!

Need your help with something I'm stuck with.

I'm not able to connect to the 'Client' instance as a Domain Admin. Getting a login attempt failed. Local Admin works.

I'm 100% certain I'm using the right password. I have deleted and recreated the stack twice already.

I have tried all variations:

1. Admin@ad.animals4life.org
2. A4L\Admin
3. ad.animals4life.org\Admin

Any ideas?

Appreciate your help.

https://github.com/acantril/learn-cantrill-io-labs/blob/master/aws-hybrid-activedirectory/02_LABINSTRUCTIONS/STAGE2%20-%20Connect%20to%20the%20ONPREMISES%20Jumpbox.md

**Comment by ptal3** [comment]
Digging into the CloudWatch logs, seems like the Powershell scripts are failing:

At C:\AWSQuickstart\Module-AD\Module-AD.psm1:1455 char:9
+         Import-DscResource -ModuleName 'AuditPolicyDsc'
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'AuditPolicyDsc'.
At C:\AWSQuickstart\Module-AD\Module-AD.psm1:2040 char:9
+         Import-DscResource -ModuleName 'AuditPolicyDsc'
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'AuditPolicyDsc'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ModuleNotFoundDuringParse
 
Import-Module : The specified module 'C:\AWSQuickstart\Module-AD\Module-AD.psm1' was not loaded because no valid 
module file was found in any module directory.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0de7f58f9c3c2f3e2\document\orchestration\f3fa5751-66f1-4f7e-892f-c4009df51b
2a\awsrunPowerShellScript\0.awsrunPowerShellScript\_script.ps1:2 char:5
+     Import-Module -Name 'C:\AWSQuickstart\Module-AD\Module-AD.psm1' - ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\AWSQuickstar...\Module-AD.psm1:String) [Import-Module], FileNot 
   FoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
New-VolumeFromRawDisk : The term 'New-VolumeFromRawDisk' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0de7f58f9c3c2f3e2\document\orchestration\f3fa5751-66f1-4f7e-892f-c4009df51b
2a\awsrunPowerShellScript\0.awsrunPowerShellScript\_script.ps1:7 char:1
+ New-VolumeFromRawDisk
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-VolumeFromRawDisk:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Invoke-PreConfig : The term 'Invoke-PreConfig' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0de7f58f9c3c2f3e2\document\orchestration\f3fa5751-66f1-4f7e-892f-c4009df51b
2a\awsrunPowerShellScript\0.awsrunPowerShellScript\_script.ps1:8 char:1
+ Invoke-PreConfig
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-PreConfig:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Invoke-LcmConfig : The term 'Invoke-LcmConfig' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At C:\ProgramData\Amazon\SSM\InstanceData\i-0de7f58f9c3c2f3e2\document\orchestration\f3fa5751-66f1-4f7e-892f-c4009df51b
2a\awsrunPowerShellScript\0.awsrunPowerShellScript\_script.ps1:9 char:1
+ Invoke-LcmConfig
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-LcmConfig:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ptal3** [comment]
Hi @acantril,

Issue resolved.

A missing "AuditPolicyDSC" module dependency needs to be added onto 
https://learn-cantrill-labs.s3.amazonaws.com/aws-hybrid-activedirectory/03_HYBRIDDIR-NESTED-ONPREM-AD-v2.yaml.

Snippet below:

$Modules = @(
                      @{
                          Name = 'NetworkingDsc'
                          Version = '8.2.0'
                      },
                      @{
                          Name = 'ActiveDirectoryDsc'
                          Version = '6.0.1'
                      },
                      @{
                          Name = 'ComputerManagementDsc'
                          Version = '8.4.0'
                      },
                      @{
                          Name = 'DnsServerDsc'
                          Version = '3.0.0'
                      }**_**_,
                      @{
                          Name = 'AuditPolicyDsc'
                          Version = '1.4.0.0'
                      }_**_**
                  )

**Comment by acantril** [comment]
Hi
This demo is broken
i'm working on replacing, but it says in the course not to do it.

**Comment by ptal3** [comment]
Thank you @acantril, much appreciated!
