### ISSUE TITLE
CatPipeline - STAGE4 - Deploy our Container w/ CodeDeploy - PART1

### ISSUE THREAD

**Issue by adsz** [acantril/learn-cantrill-io-labs#90]
By default AWS Console opens in a new layout so all ECS related steps look different and I had to switch to the old layout to be able to follow the instructions provided in this lesson.

_"The new experience is now the default
The new experience is now the default in the Amazon ECS console. You can now use the new simplified workflows for deploying tasks and services, task definition JSON editor, and other new features. You can temporarily switch to the classic console for any unsupported features, but your preference will be reset after a session."_

Furthermore, while creating Task Definition, the Task role drop-down is empty so I can't select the ecsTaskExecutionRole.

Any suggestions how to progress from there?

**Comment by acantril** [comment]
Good find, I've been waiting for this to happen for a while, looks like it just switched. Hopefully the same is true on all accounts. Thanks again.

**Comment by acantril** [comment]
Updated the entire demo.
Updated in courses, youtube versions will happen shortly.
