### ISSUE TITLE
Videos are marked private?

### ISSUE THREAD

**Issue by cpayne22** [acantril/learn-cantrill-io-labs#96]
Not sure if I've missed something.  These videos seem to be marked as private on youtube?

**Comment by cpayne22** [comment]
For example:  https://github.com/acantril/learn-cantrill-io-labs/tree/master/aws-codepipeline-catpipeline

**Comment by acantril** [comment]
Should be fixed, they were pointing at the old videos.
I just did an update a few days ago with the new UI.

**Comment by cpayne22** [comment]
Nice!
